/* NOXCAT BLOCK RUN — canvas-only game systems: Game, Player, Level, Collision, Camera, UI, Audio */
(()=>{'use strict';
const c=document.querySelector('#game'),x=c.getContext('2d'),W=c.width,H=c.height, $=s=>document.querySelector(s);
x.imageSmoothingEnabled=false; const hud={hp:$('#hp'),energy:$('#energy'),score:$('#score'),time:$('#time')};
const key={left:false,right:false,jump:false,press:false}; let state='title',last=0,game, img=new Image(),enemyImg=new Image(),tokenImg=new Image(),platformImg=new Image(),backgroundImg=new Image(); img.src='assets/player/noxcat-spritesheet-clean.png';enemyImg.src='assets/enemies/nox-enemies-clean.png';tokenImg.src='assets/ui/energy-token-clean.png';platformImg.src='assets/blocks/platform-atlas-clean.png';backgroundImg.src='assets/background/cyber-city-background.png';
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n)), hit=(a,b)=>a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y; let debugSprites=false;
const questions=[
['什麼是區塊鏈（Blockchain）？','一種去中心化的分散式帳本技術','一種手機作業系統','一種傳統銀行服務',0],['區塊鏈最大的特色之一是什麼？','所有資料都由單一公司控制','資料可以由網路上的多個節點共同驗證','只能在沒有網路的環境使用',1],['區塊鏈中的「區塊」主要用來做什麼？','儲存與記錄交易等資料','增加手機容量','加速 Wi-Fi',0],['什麼是加密貨幣？','只能用現金購買的商品','建立在密碼學與區塊鏈等技術上的數位資產','一種實體紙鈔',1],['什麼是錢包（Wallet）？','用來管理區塊鏈資產與交易的工具','只能存放現金的皮夾','用來提高手機畫質的 App',0],['區塊鏈錢包中的私鑰最重要的用途是什麼？','控制與授權相關區塊鏈資產','增加網路速度','取得手機號碼',0],['什麼是智能合約？','一種紙本合約','部署在區塊鏈上的程式，可按規則執行','銀行人工審核流程',1],['什麼是 Gas Fee？','區塊鏈交易或執行操作時的網路費用','購買手機的費用','銀行月租費',0],['去中心化代表什麼？','所有資料只存在一台電腦','控制與驗證不完全依賴單一中心機構','必須由政府管理',1],['什麼是代幣（Token）？','可代表價值、權利或用途的數位資產','一種實體硬幣','一種電腦螢幕',0],['什麼是 DeFi？','Decentralized Finance，去中心化金融','Digital File，數位檔案','Device Finder，裝置搜尋工具',0],['什麼是 RWA？','Real World Assets，現實世界資產代幣化','Random Web Application','Remote Wallet Address',0],['什麼是 NFT？','Non-Fungible Token，具有獨特性的非同質化代幣','一種網路瀏覽器','一種加密演算法',0],['多鏈（Multi-chain）通常指什麼？','只能使用一條區塊鏈','支援或使用多個不同區塊鏈網路','只能使用比特幣',1],['為什麼鏈上交易通常可以公開查詢？','許多公鏈具有公開可驗證的鏈上資料','所有人必須公開密碼','銀行會公布所有資料',0],['NOXCAT 主要定位為什麼？','Web3 基礎設施與金融應用平台','線上影音平台','電腦作業系統',0],['NOXCAT 的生態系統主要建立在哪條區塊鏈上？','Arbitrum','Dogecoin','Litecoin',0],['NOXCAT 的原生代幣名稱是什麼？','$NOX','$BTC','$ETH',0],['NOXCAT Wallet 的主要用途是什麼？','管理數位資產並提供 Web3 相關功能','只用來觀看影片','只用來玩單機遊戲',0],['NOXCAT Wallet 的特色之一是什麼？','整合錢包、社交功能與資產管理','完全不能資產管理','只能存放紙鈔',0],['NOXCAT Wallet 可透過哪些方式社交登入？','Google、Apple 或 Email','只能使用銀行存摺','只能使用信用卡',0],['NOXCAT Wallet 中的 UID 主要可以做什麼？','作為生態系中的使用者識別方式之一','增加手機容量','取代區塊鏈本身',0],['NOXCAT Wallet 採用哪一種安全架構？','MPC','GPS','NFC',0],['MPC 的概念主要是什麼？','將關鍵控制資訊以多方計算分散處理','把私鑰公開在網路上','所有資料存放在一台伺服器',0],['NOXCAT Escrow 的主要功能是什麼？','以智能合約鎖定資金並依條件結算','觀看區塊鏈影片','提高手機電池容量',0],['在 NOXCAT Escrow 中資金可如何處理？','先鎖定在智能合約中，符合條件再釋放','直接交陌生人保管','必須轉成現金交易',0],['NOXCAT Wallet 的社交轉帳主要解決什麼？','降低直接操作長錢包地址的複雜度','完全不需要區塊鏈','讓所有交易變現金',0],['NOXCAT Staking 主要與什麼有關？','生態參與、獎勵與安全機制','手機充電','硬碟格式化',0],['$NOX 未來可用於哪些方向？','治理、支付／轉帳及生態功能','只能購買手機','只能支付電費',0],['NOXCAT 的核心目標是什麼？','降低一般使用者接觸 Web3 的複雜度','讓 Web3 更難使用','完全取消區塊鏈技術',0]
].map(([q,a,b,c,ok])=>({q,a:[a,b,c],ok}));
const quiz=document.createElement('section');quiz.id='quiz';quiz.className='hidden';document.querySelector('#game-shell').appendChild(quiz);
class AudioKit{constructor(){this.ctx=null;this.music=0} boot(){if(!this.ctx)this.ctx=new (window.AudioContext||window.webkitAudioContext)()} beep(type='jump'){this.boot();let a=this.ctx,t=a.currentTime,o=a.createOscillator(),g=a.createGain(),m={jump:[480,0.09,'square'],step:[140,.045,'square'],collect:[850,.08,'sine'],hit:[100,.18,'sawtooth'],stomp:[170,.12,'square'],check:[620,.2,'triangle'],win:[520,.45,'triangle'],over:[90,.5,'sawtooth']}[type]||[300,.1,'square'];o.type=m[2];o.frequency.setValueAtTime(m[0],t);o.frequency.exponentialRampToValueAtTime(type==='jump'?800:Math.max(30,m[0]*.65),t+m[1]);g.gain.setValueAtTime(type==='step'?.035:.085,t);g.gain.exponentialRampToValueAtTime(.001,t+m[1]);o.connect(g).connect(a.destination);o.start(t);o.stop(t+m[1])} musicOn(){if(this.music)return;this.boot();this.music=setInterval(()=>{if(state==='playing'){let n=[220,277,330,415][Math.floor(Math.random()*4)];let o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type='square';o.frequency.value=n;g.gain.value=.042;o.connect(g).connect(this.ctx.destination);o.start();o.stop(this.ctx.currentTime+.09)}},280)}} const sfx=new AudioKit();
class Player{constructor(){this.w=48;this.h=66;this.reset(90,520)}reset(px,py){Object.assign(this,{x:px,y:py,vx:0,vy:0,ground:false,jumps:0,face:1,inv:0,anim:0,stepClock:0,mode:'idle'})}update(dt){let ax=(key.right?1:0)-(key.left?1:0);this.vx+=ax*1800*dt;this.vx*=.94;this.vx=clamp(this.vx,-300,300);if(ax)this.face=ax;if(key.press&&this.jumps<2){this.vy=this.jumps? -520:-590;this.jumps++;this.ground=false;sfx.beep('jump')}key.press=false;this.vy+=1450*dt;this.vy=Math.min(this.vy,850);this.x+=this.vx*dt;this.x=clamp(this.x,0,game.level.width-this.w);this.y+=this.vy*dt;this.ground=false;for(const p of game.level.platforms){if(p.dead)continue;if(this.vy>=0&&this.y+this.h>=p.y&&this.y+this.h-this.vy*dt<=p.y&&this.x+this.w>p.x&&this.x<p.x+p.w){this.y=p.y-this.h;this.vy=0;this.ground=true;this.jumps=0;if(p.type==='bounce'){this.vy=-820;this.jumps=1;sfx.beep('jump')}if(p.type==='break'){p.steps=(p.steps||0)+1;if(p.steps>=3){p.dead=true;game.spark(p.x+p.w/2,p.y,'#ffbf5d',12)}}}}if(this.y>H+180)game.damage(true);this.inv=Math.max(0,this.inv-dt);this.anim+=dt;this.stepClock+=dt;if(this.ground&&Math.abs(this.vx)>80&&this.stepClock>.23){sfx.beep('step');this.stepClock=0}if(!this.ground)this.stepClock=.18;this.mode=this.inv?'hurt':!this.ground?(this.vy<0?'jump':'fall'):Math.abs(this.vx)>50?'run':'idle'}draw(){if(this.inv>0&&Math.floor(this.inv*12)%2)return;let frame=this.mode==='run'?Math.floor(this.anim*10)%2:this.mode==='jump'?3:this.mode==='fall'?4:this.mode==='hurt'?1:0;if(img.complete&&img.naturalWidth){let sw=img.naturalWidth/6,sh=img.naturalHeight/4; x.save();x.translate(this.x+this.w/2-game.cam,this.y+this.h/2);x.scale(this.face,1);x.drawImage(img,(frame%6)*sw,0,sw,sh,-38,-52,76,104);x.restore()}else drawCat(this.x-game.cam,this.y,this.w,this.h,this.face)}}
class Level{constructor(){this.width=7600;this.platforms=[];this.enemies=[];this.energy=[];this.beacons=[{x:2500,y:480,on:false},{x:5050,y:450,on:false}];this.core={x:7240,y:390,w:110,h:155}; this.make()}p(x,y,w,type='stone',opts={}){this.platforms.push({x,y,w,h:34,type,...opts})}make(){// 27 hand-built, forgiving original block platforms
this.p(0,600,680);this.p(760,600,400,'metal');this.p(1250,570,370,'pulse');this.p(1710,600,650);this.p(2460,560,560,'stone');this.p(3100,600,520,'metal');this.p(3720,570,580,'pulse');this.p(4380,600,630);this.p(5120,540,560,'stone');this.p(5780,600,610,'metal');this.p(6480,560,1050,'stone');
[[350,470,150,'energy'],[800,470,130,'bounce'],[1060,400,130,'float'],[1410,430,130,'break'],[1580,350,120,'float'],[1900,450,160,'metal'],[2220,380,120,'hazard'],[2550,420,150,'energy'],[2850,360,150,'break'],[3300,450,140,'bounce'],[3500,350,120,'float'],[3850,420,150,'metal'],[4150,350,150,'hazard'],[4560,430,150,'energy'],[4820,340,120,'break'],[5260,370,140,'bounce'],[5500,300,120,'float'],[5900,430,160,'metal'],[6200,350,140,'hazard'],[6700,400,150,'energy'],[7000,310,140,'float']].forEach(a=>this.p(...a));
[[710,520,220,0],[1850,520,210,1],[2670,470,220,2]].forEach(a=>this.platforms.push({x:a[0],y:a[1],w:130,h:30,type:'moving',base:a[0],range:a[2],phase:a[3],h:30}));
for(let i=0;i<43;i++){let px=220+i*165+(i%3)*22,py=420-(i%5)*32;this.energy.push({x:px,y:py,on:true,t:i*.4})}for(let i=0;i<15;i++)this.spawnEnemy(i%3?'bot':'beetle',620+i*470,i)}spawnEnemy(type,spawnX,index){let w=type==='bot'?46:52,h=type==='bot'?44:38,center=spawnX+w/2;let candidates=this.platforms.filter(p=>!p.dead&&center>=p.x+6&&center<=p.x+p.w-6).sort((a,b)=>a.y-b.y);let ground=candidates[0];if(!ground){console.warn('[EnemySpawn] no supporting platform',type,spawnX);return}let enemy={x:spawnX,y:ground.y-h,w,h,v:index%2?65:-65,type,dead:false,t:index,spawn:{x:spawnX,y:ground.y-h,platformY:ground.y},questionLock:false,questionCooldown:0};this.enemies.push(enemy);if(debugSprites)console.info('[EnemySpawn]',type,enemy.spawn)}update(dt,t){for(const p of this.platforms)if(p.type==='moving'){p.x=p.base+Math.sin(t*1.15+p.phase)*p.range/2}for(const e of this.enemies){if(e.dead)continue;e.x+=e.v*dt*(e.type==='beetle'&&Math.sin(t+e.t)>0.82?2.5:1);let base=this.platforms.find(p=>e.x+e.w/2>p.x&&e.x+e.w/2<p.x+p.w&&Math.abs(p.y-(e.y+e.h))<3);if(!base||e.x<base.x||e.x+e.w>base.x+base.w)e.v*=-1}for(const e of this.energy)e.t+=dt}draw(){for(const p of this.platforms)if(!p.dead)drawBlock(p);for(const e of this.energy)if(e.on)drawEnergy(e);for(const b of this.beacons)drawBeacon(b);drawCore(this.core);for(const e of this.enemies)if(!e.dead)drawEnemy(e)}}
function drawBlock(p){let X=p.x-game.cam,Y=p.y;if(X+p.w<0||X>W)return;let col={stone:'#3f5061',metal:'#8196a4',pulse:'#1a2752',energy:'#24633f',float:'#516a8e',break:'#8a5b45',bounce:'#167f91',hazard:'#a43e43',moving:'#4f819d'}[p.type]||'#3f5061';x.fillStyle='#10172d';x.fillRect(X-4,Y-4,p.w+8,p.h+8);x.fillStyle='#080d1b';x.fillRect(X-2,Y-2,p.w+4,p.h+4);x.fillStyle=col;x.fillRect(X,Y,p.w,p.h);x.fillStyle='#ffffff26';x.fillRect(X+3,Y+3,p.w-6,4);for(let q=0;q<p.w;q+=32){x.fillStyle=p.type==='hazard'?'#ff8a54':p.type==='bounce'?'#a0ffe2':p.type==='pulse'?'#75ffb0':'#d6e5e9';x.fillRect(X+q+5,Y+8,18,3);x.fillStyle='#243452';x.fillRect(X+q+3,Y+24,23,4);x.fillStyle='#0b1428';x.fillRect(X+q+26,Y+4,3,25)}if(p.type==='hazard'){x.fillStyle='#ffe37a';for(let q=8;q<p.w;q+=30){x.beginPath();x.moveTo(X+q,Y+27);x.lineTo(X+q+8,Y+7);x.lineTo(X+q+16,Y+27);x.fill()}}if(p.type==='break'){x.strokeStyle='#ffd8ae';x.beginPath();x.moveTo(X+10,Y+5);x.lineTo(X+20,Y+27);x.lineTo(X+31,Y+12);x.stroke()}}
function drawCat(X,Y,w,h,f){x.fillStyle='#141c23';x.fillRect(X,Y,w,h);x.fillStyle='#9dff20';x.fillRect(X+9,Y+17,9,7);x.fillRect(X+29,Y+17,9,7);x.fillStyle='#e9f5e9';x.fillRect(X+6,Y+42,12,12);x.fillRect(X+30,Y+42,12,12)}
function drawEnemy(e){let X=e.x-game.cam,Y=e.y;if(enemyImg.complete&&enemyImg.naturalWidth){let sw=enemyImg.naturalWidth/7,sh=enemyImg.naturalHeight/3,frame=Math.floor((game.t+e.t)*7)%5;x.save();if(e.v<0){x.translate(X+e.w,Y);x.scale(-1,1);X=0;Y=0}x.drawImage(enemyImg,frame*sw,e.type==='bot'?0:sh,sw,sh,X-6,Y-8,e.w+12,e.h+14);x.restore();return}x.fillStyle='#101421';x.fillRect(X,Y,e.w,e.h)}
function drawEnergy(e){let X=e.x-game.cam,Y=e.y+Math.sin(e.t*3)*6;x.save();x.translate(X,Y);x.rotate(e.t*2.4);if(tokenImg.complete&&tokenImg.naturalWidth){x.drawImage(tokenImg,-18,-18,36,36)}else{x.fillStyle='#ffbc31';x.fillRect(-7,-12,14,24)}x.restore()}
function drawBeacon(b){let X=b.x-game.cam,Y=b.y;x.fillStyle='#162c32';x.fillRect(X,Y,28,80);x.fillStyle=b.on?'#68ff89':'#31534a';x.shadowColor='#68ff89';x.shadowBlur=b.on?16:0;x.fillRect(X+7,Y+14,14,33);x.shadowBlur=0;x.fillStyle='#9caeb0';x.fillRect(X-7,Y+78,42,8)}function drawCore(o){let X=o.x-game.cam,Y=o.y, pulse=1+Math.sin(game.t*4)*.08;x.fillStyle='#243a3c';x.fillRect(X,Y+22,o.w,o.h-22);x.fillStyle='#62ff8b';x.shadowColor='#62ff8b';x.shadowBlur=25;x.beginPath();x.arc(X+o.w/2,Y+62,31*pulse,0,7);x.fill();x.shadowBlur=0;x.fillStyle='#e6fff1';x.fillRect(X+o.w/2-6,Y+33,12,56);x.fillStyle='#7b8f94';x.fillRect(X+12,Y+118,o.w-24,12)}
class Game{constructor(){this.level=new Level();this.player=new Player();this.cam=0;this.time=180;this.score=0;this.count=0;this.combo=0;this.check={x:90,y:520};this.particles=[];this.t=0}start(){this.level=new Level();this.player=new Player();this.cam=0;this.time=180;this.score=this.count=this.combo=0;this.check={x:90,y:520};this.particles=[];this.t=0;state='playing';$('#overlay').classList.add('hidden');sfx.musicOn();this.ui()}spark(X,Y,col,n){for(let i=0;i<n;i++)this.particles.push({x:X,y:Y,vx:(Math.random()-.5)*250,vy:-Math.random()*250,col,life:.6})}damage(fall=false){let p=this.player;if(p.inv>0&&!fall)return;p.inv=1.3;p.vx=0;p.vy=0;this.combo=0;this.spark(p.x+p.w/2,p.y,'#ff705f',14);sfx.beep('hit');this.hp=(this.hp??3)-1;if(this.hp<=0){this.end(false);return}p.reset(this.check.x,this.check.y);this.cam=Math.max(0,this.check.x-W*.35)}end(win){if(state!=='playing')return;state=win?'win':'over';if(win){this.score+=1000+Math.floor(this.time)*10;sfx.beep('win')}else sfx.beep('over');$('#overlay').classList.remove('hidden');$('#start').textContent=win?'PLAY AGAIN':'TRY AGAIN';$('#message').textContent=win?'MISSION COMPLETE':'SYSTEM FAILURE';$('#result').innerHTML=win?`TIME ${Math.ceil(this.time)} &nbsp; SCORE ${this.score}<br>ENERGY ${this.count} &nbsp; MAX COMBO ${this.combo}`:'The digital ruins rebooted you at the last beacon.'}ui(){hud.hp.textContent='HP: '+ '♥'.repeat(this.hp??3)+'♡'.repeat(3-(this.hp??3));hud.energy.textContent='ENERGY: '+String(this.count).padStart(3,'0');hud.score.textContent='SCORE: '+String(this.score).padStart(4,'0');hud.time.textContent='TIME: '+Math.ceil(this.time);hud.time.classList.toggle('warn',this.time<30)}update(dt){if(state!=='playing')return;this.t+=dt;this.time-=dt;if(this.time<=0){this.time=0;this.end(false);return}this.level.update(dt,this.t);this.player.update(dt);let p=this.player;for(const e of this.level.energy)if(e.on&&hit(p,{x:e.x-14,y:e.y-18,w:28,h:36})){e.on=false;this.count++;this.score+=100;this.combo++;sfx.beep('collect');this.spark(e.x,e.y,'#62ff8b',7)}for(const b of this.level.beacons)if(!b.on&&hit(p,{x:b.x,y:b.y,w:30,h:85})){b.on=true;this.check={x:b.x+35,y:b.y-68};this.score+=250;sfx.beep('check');this.spark(b.x+15,b.y+20,'#62ff8b',14)}for(const e of this.level.enemies)if(!e.dead&&hit(p,e)){if(p.vy>100&&p.y+p.h-e.y<25){e.dead=true;p.vy=-390;this.score+=200;this.combo++;sfx.beep('stomp');this.spark(e.x+20,e.y,'#a47cff',10)}else this.damage()}for(const q of this.level.platforms)if(q.type==='hazard'&&hit(p,q))this.damage();if(hit(p,this.level.core))this.end(true);this.cam+=((clamp(p.x-W*.42,0,this.level.width-W))-this.cam)*Math.min(1,dt*5);for(const z of this.particles){z.x+=z.vx*dt;z.y+=z.vy*dt;z.vy+=500*dt;z.life-=dt}this.particles=this.particles.filter(z=>z.life>0);this.ui()}draw(){drawBG();this.level.draw();this.player.draw();for(const z of this.particles){x.globalAlpha=z.life*1.5;x.fillStyle=z.col;x.fillRect(z.x-game.cam,z.y,5,5)}x.globalAlpha=1}}
function drawBG(){let sky=x.createLinearGradient(0,0,0,H);sky.addColorStop(0,'#1b2458');sky.addColorStop(.56,'#314c80');sky.addColorStop(1,'#1c3851');x.fillStyle=sky;x.fillRect(0,0,W,H);let cam=game?game.cam:0;for(let layer=0;layer<3;layer++){let f=[.12,.25,.45][layer],base=[305,380,485][layer];x.fillStyle=['#27376b','#2a5178','#315d6b'][layer];for(let q=-120;q<W+160;q+=130){let h=70+((Math.floor((q+cam*f)/130)*43)%150+150)%150;x.fillRect(q,base-h,82,h);x.fillStyle=layer===1?'#498499':'#1a3158';x.fillRect(q+10,base-h+18,8,12);x.fillStyle='#90ffad';x.fillRect(q+30,base-h+38,8,4)}}x.fillStyle='#b8ff7a';x.globalAlpha=.42;for(let i=0;i<40;i++){let px=(i*157-cam*.08)%W,py=70+(i*83)%380;x.fillRect(px,py,2,2)}x.globalAlpha=1;x.fillStyle='#163650';x.fillRect(0,640,W,80)}
function loop(now){let dt=Math.min(.033,(now-last)/1000||0);last=now;if(game){game.update(dt);game.draw()}requestAnimationFrame(loop)}
function start(){sfx.boot();game=new Game();game.hp=3;game.start()} $('#start').onclick=start;$('#controls').onclick=()=>{$('#message').textContent='左右移動，SPACE / W 跳躍。空中再按一次可二段跳。踩擊敵人、啟動兩座 Beacon，前往 NOX CORE。'};
addEventListener('keydown',e=>{let k=e.code;if(['ArrowLeft','ArrowRight','Space','KeyA','KeyD','KeyW'].includes(k))e.preventDefault();if(k==='ArrowLeft'||k==='KeyA')key.left=true;if(k==='ArrowRight'||k==='KeyD')key.right=true;if((k==='Space'||k==='KeyW')&&!key.jump){key.press=true;key.jump=true}});addEventListener('keyup',e=>{let k=e.code;if(k==='ArrowLeft'||k==='KeyA')key.left=false;if(k==='ArrowRight'||k==='KeyD')key.right=false;if(k==='Space'||k==='KeyW')key.jump=false});
document.querySelectorAll('#touch button').forEach(b=>{let n=b.dataset.key,down=e=>{e.preventDefault();if(n==='jump'){if(!key.jump)key.press=true;key.jump=true}else key[n]=true},up=e=>{e.preventDefault();if(n==='jump')key.jump=false;else key[n]=false};b.addEventListener('touchstart',down,{passive:false});b.addEventListener('touchend',up,{passive:false});b.addEventListener('touchcancel',up,{passive:false});b.addEventListener('mousedown',down);b.addEventListener('mouseup',up);b.addEventListener('mouseleave',up)});game=new Game();requestAnimationFrame(loop);
// Canonical atlas metadata. Source rectangles are measured from the supplied transparent PNGs;
// destination rectangles below are visual-only and never alter entity collision boxes.
const SPRITES={
 player:{idle:{sx:45,sy:42,sw:150,sh:195},runA:{sx:238,sy:42,sw:150,sh:195},runB:{sx:418,sy:42,sw:178,sh:195},jump:{sx:580,sy:42,sw:185,sh:205},fall:{sx:775,sy:42,sw:185,sh:205},hurt:{sx:955,sy:42,sw:184,sh:205}},
 enemy:{blockBot:[{sx:34,sy:190,sw:170,sh:180},{sx:218,sy:190,sw:185,sh:180},{sx:420,sy:190,sw:190,sh:180},{sx:616,sy:190,sw:190,sh:180}],glitchBeetle:[{sx:34,sy:570,sw:185,sh:170},{sx:225,sy:570,sw:190,sh:170},{sx:430,sy:570,sw:190,sh:170},{sx:636,sy:570,sw:190,sh:170}]}
};
const PLATFORM_SPRITES={stone:{sx:70,sy:130,sw:430,sh:210},metal:{sx:540,sy:135,sw:410,sh:210},pulse:{sx:990,sy:150,sw:460,sh:190},energy:{sx:70,sy:420,sw:430,sh:210},float:{sx:540,sy:410,sw:390,sh:220},break:{sx:1010,sy:420,sw:410,sh:220},bounce:{sx:75,sy:690,sw:380,sh:190},hazard:{sx:540,sy:670,sw:390,sh:210},moving:{sx:1000,sy:700,sw:450,sh:160}};
drawBlock=function(p){let X=p.x-game.cam,Y=p.y,f=PLATFORM_SPRITES[p.type]||PLATFORM_SPRITES.stone;if(X+p.w<0||X>W)return;if(platformImg.complete&&platformImg.naturalWidth){let tileW=p.h*(f.sw/f.sh),count=Math.max(1,Math.floor(p.w/tileW)),used=count*tileW,start=X+(p.w-used)/2;for(let i=0;i<count;i++)x.drawImage(platformImg,f.sx,f.sy,f.sw,f.sh,start+i*tileW,Y,tileW,p.h);return}x.fillStyle='#3f5061';x.fillRect(X,Y,p.w,p.h)};
drawBG=function(){if(backgroundImg.complete&&backgroundImg.naturalWidth){x.drawImage(backgroundImg,0,0,backgroundImg.naturalWidth,backgroundImg.naturalHeight,0,0,W,H);x.fillStyle='#08113755';x.fillRect(0,0,W,H);return}x.fillStyle='#172b54';x.fillRect(0,0,W,H)};
debugSprites=false;
Player.prototype.draw=function(){if(this.inv>0&&Math.floor(this.inv*12)%2)return;let name=this.mode==='run'?(Math.floor(this.anim*9)%2?'runA':'runB'):this.mode==='jump'?'jump':this.mode==='fall'?'fall':this.mode==='hurt'?'hurt':'idle',f=SPRITES.player[name];if(img.complete&&img.naturalWidth){let dw=70,dh=90,dx=this.x+this.w/2-dw/2-game.cam,dy=this.y+this.h-dh;x.save();if(this.face<0){x.translate(dx+dw/2,0);x.scale(-1,1);dx=-dw/2}else dx=dx;x.drawImage(img,f.sx,f.sy,f.sw,f.sh,dx,dy,dw,dh);x.restore();if(debugSprites){x.strokeStyle='#4dff92';x.strokeRect(this.x-game.cam,this.y,this.w,this.h)}}else drawCat(this.x-game.cam,this.y,this.w,this.h,this.face)};
drawEnemy=function(e){if(!(enemyImg.complete&&enemyImg.naturalWidth))return;let frames=e.type==='bot'?SPRITES.enemy.blockBot:SPRITES.enemy.glitchBeetle,f=frames[Math.floor(game.t*7+e.t)%frames.length],dw=64,dh=58,dx=e.x+e.w/2-dw/2-game.cam,dy=e.y+e.h-dh;x.save();if(e.v<0){x.translate(dx+dw/2,0);x.scale(-1,1);dx=-dw/2}else dx=dx;x.drawImage(enemyImg,f.sx,f.sy,f.sw,f.sh,dx,dy,dw,dh);x.restore();if(debugSprites){x.strokeStyle='#ff82ee';x.strokeRect(e.x-game.cam,e.y,e.w,e.h)}};
const baseDamage=Game.prototype.damage;
Game.prototype.damage=function(fall=false){baseDamage.call(this,fall);if(this.hp>0&&state==='playing')this.player.inv=1.35};
Game.prototype.askQuestion=function(enemy){if(state!=='playing'||enemy.questionLock||enemy.questionCooldown>0)return;enemy.questionLock=true;state='quiz';console.debug('[EnemyCollision]',enemy.type,'Player',this.player.x,this.player.y);let q=questions[Math.floor(Math.random()*questions.length)];this.questionEnemy=enemy;quiz.innerHTML='<div class="quiz-card"><p class="quiz-tag">NOXCAT CHAIN CHECK</p><h2>'+q.q+'</h2><div class="quiz-options">'+q.a.map((a,i)=>'<button data-answer="'+i+'">'+String.fromCharCode(65+i)+'. '+a+'</button>').join('')+'</div><p class="quiz-note">答對：安全通過並獲得 +150 分　答錯：扣除 1 HP</p></div>';quiz.classList.remove('hidden');console.debug('[Question] QuestionTriggered: true');quiz.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{let correct=Number(b.dataset.answer)===q.ok;quiz.classList.add('hidden');state='playing';enemy.questionLock=false;enemy.questionCooldown=1.5;console.debug('[Answer] Correct:',correct);if(correct){enemy.dead=true;this.score+=350;this.player.inv=1.1;sfx.beep('stomp');this.spark(enemy.x+enemy.w/2,enemy.y,'#aaff8d',14);console.debug('[Enemy] EnemyDefeated: true')}else{this.damage(false);console.debug('[Damage] DamageApplied: true PlayerHP:',this.hp)}this.ui()})};
const stableGameUpdate=Game.prototype.update;
Game.prototype.update=function(dt){if(state!=='playing')return;this.t+=dt;this.time=Math.max(0,this.time-dt);if(this.time===0){this.end(false);return}this.level.update(dt,this.t);this.player.update(dt);let p=this.player;for(const e of this.level.energy)if(e.on&&hit(p,{x:e.x-14,y:e.y-18,w:28,h:36})){e.on=false;this.count++;this.score+=100;this.combo++;sfx.beep('collect');this.spark(e.x,e.y,'#62ff8b',7)}for(const b of this.level.beacons)if(!b.on&&hit(p,{x:b.x,y:b.y,w:30,h:85})){b.on=true;this.check={x:b.x+35,y:b.y-68};this.score+=250;sfx.beep('check');this.spark(b.x+15,b.y+20,'#62ff8b',14)}for(const e of this.level.enemies){e.questionCooldown=Math.max(0,(e.questionCooldown||0)-dt);if(e.dead||!hit(p,e))continue;let topHit=p.vy>100&&p.y+p.h-e.y<=16&&p.y<e.y;if(topHit){e.dead=true;p.vy=-390;this.score+=200;this.combo++;sfx.beep('stomp');this.spark(e.x+e.w/2,e.y,'#aaff8d',10);continue}if(!e.questionLock&&e.questionCooldown<=0&&p.inv<=0){this.askQuestion(e);return}}for(const q of this.level.platforms)if(q.type==='hazard'&&hit(p,q))this.damage();if(hit(p,this.level.core))this.end(true);this.cam+=((clamp(p.x-W*.42,0,this.level.width-W))-this.cam)*Math.min(1,dt*5);for(const z of this.particles){z.x+=z.vx*dt;z.y+=z.vy*dt;z.life-=dt}this.particles=this.particles.filter(z=>z.life>0);this.ui()};
const baseGameDraw=Game.prototype.draw;
Game.prototype.draw=function(){baseGameDraw.call(this);if(debugSprites){x.strokeStyle='#59dfff';for(const p of this.level.platforms)if(!p.dead)x.strokeRect(p.x-this.cam,p.y,p.w,p.h);x.fillStyle='#fff';x.font='12px monospace';x.fillText('DEBUG: F3 toggle | state '+state+' | HP '+(this.hp??3),16,78)}};
addEventListener('keydown',e=>{if(e.code==='F3'){e.preventDefault();debugSprites=!debugSprites}});
})();
